package com.project.accounting.repository;

import java.util.List;
import java.util.stream.Stream;

import org.springframework.data.jpa.repository.JpaRepository;

import com.project.accounting.model.ChartOfAccount;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

import javax.transaction.Transactional;

public interface ChartOfAccountRepository extends JpaRepository<ChartOfAccount, Long> {

//	Show All ChartOfAccount By Company(Automatically generated by repository)
	List<ChartOfAccount> findByCompany(@Param("company") int company);

//	Show All Active Chart Of Account
	@Query("select ca from ChartOfAccount ca where ca.enable = 1 and ca.company = :company")
	List<ChartOfAccount> showAllActiveCa(@Param("company") int company);

//	Delete/ partially disable a Chart Of Account
	@Transactional
	@Modifying
	@Query("update ChartOfAccount ca set ca.enable = 0 where ca.id = :id and ca.company = :company")
	void disableCa(@Param("id") Long id,@Param("company") int company);

//	Find Chart Of Account by id or name
	@Query("select ca from ChartOfAccount ca where ca.company = :company and (ca.caName like \'%:searchValue%\'" +
			" or ca.caId like \'%:searchValue%\') and ca.enable= 1")
	List<ChartOfAccount> findCaByIdOrName(@Param("searchValue") String searchValue, @Param("company") int company);

//	Find By Id
	ChartOfAccount findById(ChartOfAccount id);



}
