package com.project.accounting.repository;

import java.util.List;
import java.util.stream.Stream;

import org.springframework.data.jpa.repository.JpaRepository;

import com.project.accounting.model.ChartOfAccount;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface ChartOfAccountRepository extends JpaRepository<ChartOfAccount, Long> {

//	Show All ChartOfAccount By Company(Automatically generated by repository)
	List<ChartOfAccount> findByCompany(@Param("company") int company);

//	Show All Active Chart Of Account
	@Query("select ca from ChartOfAccount ca where ca.enable = 1 and ca.company = :company")
	List<ChartOfAccount> showAllActiveCa(@Param("company") int company);

//	Delete/ partially disable a Chart Of Account
	@Query("update ChartOfAccount ca set ca.enable = 'false' where ca.id = :caId")
	void disableCa(@Param("caId") Long caId);

//	Find Chart Of Account by id or name
	@Query("select ca from ChartOfAccount ca where ca.company = :company and (ca.caName like \'%:searchValue%\'" +
			" or ca.caId like \'%:searchValue%\') and ca.enable= 1")
	List<ChartOfAccount> findCaByIdOrName(@Param("searchvalue") String searchValue, @Param("company") int company);

// company add to search



}
